# coding: utf-8

"""
    OpenAPI

    tinkoff.ru/invest OpenAPI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: n.v.melnikov@tinkoff.ru
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_genclient.configuration import Configuration


class Order(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'order_id': 'str',
        'figi': 'str',
        'operation': 'OperationType',
        'status': 'OrderStatus',
        'requested_lots': 'int',
        'executed_lots': 'int',
        'type': 'OrderType',
        'price': 'float'
    }

    attribute_map = {
        'order_id': 'orderId',
        'figi': 'figi',
        'operation': 'operation',
        'status': 'status',
        'requested_lots': 'requestedLots',
        'executed_lots': 'executedLots',
        'type': 'type',
        'price': 'price'
    }

    def __init__(self, order_id=None, figi=None, operation=None, status=None, requested_lots=None, executed_lots=None, type=None, price=None, local_vars_configuration=None):  # noqa: E501
        """Order - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._order_id = None
        self._figi = None
        self._operation = None
        self._status = None
        self._requested_lots = None
        self._executed_lots = None
        self._type = None
        self._price = None
        self.discriminator = None

        self.order_id = order_id
        self.figi = figi
        self.operation = operation
        self.status = status
        self.requested_lots = requested_lots
        self.executed_lots = executed_lots
        self.type = type
        self.price = price

    @property
    def order_id(self):
        """Gets the order_id of this Order.  # noqa: E501


        :return: The order_id of this Order.  # noqa: E501
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this Order.


        :param order_id: The order_id of this Order.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and order_id is None:  # noqa: E501
            raise ValueError("Invalid value for `order_id`, must not be `None`")  # noqa: E501

        self._order_id = order_id

    @property
    def figi(self):
        """Gets the figi of this Order.  # noqa: E501


        :return: The figi of this Order.  # noqa: E501
        :rtype: str
        """
        return self._figi

    @figi.setter
    def figi(self, figi):
        """Sets the figi of this Order.


        :param figi: The figi of this Order.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and figi is None:  # noqa: E501
            raise ValueError("Invalid value for `figi`, must not be `None`")  # noqa: E501

        self._figi = figi

    @property
    def operation(self):
        """Gets the operation of this Order.  # noqa: E501


        :return: The operation of this Order.  # noqa: E501
        :rtype: OperationType
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this Order.


        :param operation: The operation of this Order.  # noqa: E501
        :type: OperationType
        """
        if self.local_vars_configuration.client_side_validation and operation is None:  # noqa: E501
            raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501

        self._operation = operation

    @property
    def status(self):
        """Gets the status of this Order.  # noqa: E501


        :return: The status of this Order.  # noqa: E501
        :rtype: OrderStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Order.


        :param status: The status of this Order.  # noqa: E501
        :type: OrderStatus
        """
        if self.local_vars_configuration.client_side_validation and status is None:  # noqa: E501
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def requested_lots(self):
        """Gets the requested_lots of this Order.  # noqa: E501


        :return: The requested_lots of this Order.  # noqa: E501
        :rtype: int
        """
        return self._requested_lots

    @requested_lots.setter
    def requested_lots(self, requested_lots):
        """Sets the requested_lots of this Order.


        :param requested_lots: The requested_lots of this Order.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and requested_lots is None:  # noqa: E501
            raise ValueError("Invalid value for `requested_lots`, must not be `None`")  # noqa: E501

        self._requested_lots = requested_lots

    @property
    def executed_lots(self):
        """Gets the executed_lots of this Order.  # noqa: E501


        :return: The executed_lots of this Order.  # noqa: E501
        :rtype: int
        """
        return self._executed_lots

    @executed_lots.setter
    def executed_lots(self, executed_lots):
        """Sets the executed_lots of this Order.


        :param executed_lots: The executed_lots of this Order.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and executed_lots is None:  # noqa: E501
            raise ValueError("Invalid value for `executed_lots`, must not be `None`")  # noqa: E501

        self._executed_lots = executed_lots

    @property
    def type(self):
        """Gets the type of this Order.  # noqa: E501


        :return: The type of this Order.  # noqa: E501
        :rtype: OrderType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Order.


        :param type: The type of this Order.  # noqa: E501
        :type: OrderType
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def price(self):
        """Gets the price of this Order.  # noqa: E501


        :return: The price of this Order.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this Order.


        :param price: The price of this Order.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and price is None:  # noqa: E501
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Order):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Order):
            return True

        return self.to_dict() != other.to_dict()
