# coding: utf-8

"""
    OpenAPI

    tinkoff.ru/invest OpenAPI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: n.v.melnikov@tinkoff.ru
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_genclient.configuration import Configuration


class SandboxRegisterRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'broker_account_type': 'BrokerAccountType'
    }

    attribute_map = {
        'broker_account_type': 'brokerAccountType'
    }

    def __init__(self, broker_account_type=None, local_vars_configuration=None):  # noqa: E501
        """SandboxRegisterRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._broker_account_type = None
        self.discriminator = None

        if broker_account_type is not None:
            self.broker_account_type = broker_account_type

    @property
    def broker_account_type(self):
        """Gets the broker_account_type of this SandboxRegisterRequest.  # noqa: E501


        :return: The broker_account_type of this SandboxRegisterRequest.  # noqa: E501
        :rtype: BrokerAccountType
        """
        return self._broker_account_type

    @broker_account_type.setter
    def broker_account_type(self, broker_account_type):
        """Sets the broker_account_type of this SandboxRegisterRequest.


        :param broker_account_type: The broker_account_type of this SandboxRegisterRequest.  # noqa: E501
        :type: BrokerAccountType
        """

        self._broker_account_type = broker_account_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SandboxRegisterRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SandboxRegisterRequest):
            return True

        return self.to_dict() != other.to_dict()
